"""add public meeting id

Revision ID: aa05114aa4de
Revises: 74ed46465b06
Create Date: 2026-08-16 15:50:53.967691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa05114aa4de'
down_revision: Union[str, Sequence[str], None] = '74ed46465b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('public_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_meetings_public_id'), 'meetings', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_public_id'), table_name='meetings')
    op.drop_column('meetings', 'public_id')
    # ### end Alembic commands ###
